spring:
  application:
    name: service-registry
  cloud:
    config:
      enabled: true
      uri: http://localhost:8888
      fail-fast: true
server:
  port: 8761

eureka:
  instance:
    hostname: "${HOSTNAME:localhost}.eureka"
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/}
#     defaultZone: http://localhost:8761/
#eureka:
#  client:
#    fetch-registry: false
#    register-with-eureka: false
##       defaultZone: http://localhost:8761/eureka/