spring:
  config:
    import:
      configserver:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOriginPatterns:
              - "*"
            allowCredentials: true
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: question-service
          uri:
            lb://question-service
          predicates:
            - Path=/question/**
        - id: quiz-service
          uri:
            lb://quiz-service
          predicates:
            - Path=/quiz/**
        - id: contribute-service
          uri:
            lb://contribute-service
          predicates:
            - Path=/contribute/**

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${EUREKA_HOSTNAME:eureka-0}
  client:
    register-with-eureka: ${EUREKA_REGISTER_WITH_EUREKA:false}
    fetch-registry: ${EUREKA_FETCH_REGISTRY:false}
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761}
server:
  port: 8765
